services:
  web:
    build: .
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8001:8000
    env_file:
      - .dock.env
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - 5432
    env_file:
      - .dock.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}